// <auto-generated />
namespace NoOperation_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addStateANDLgaTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addStateANDLgaTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201902141034207_addStateANDLgaTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
